#pragma once

#define TILE_MAP_SIZE 4
#define HALF_TILE_MAP 2
#define STAGE_MAP_SIZE 13
#define PX_TILE_SIZE 16

#define FAST_BULLETS_TRIGGER 1
#define MULTIPLE_BULLETS_TRIGGER 2
#define SUPER_BULLETS_TRIGGER 3

#define MAX_NUMBER_OF_STARS 3
#define MAX_AVAILABLE_TANKS 20
#define MAX_NUMBER_OF_LIVES 9
#define DEFAULT_NUMBER_OF_LIVES 3

#define BULLET_SIZE 1
#define SUPER_BULLET_SIZE 5

#define TURN_RATE 4

#define STOP_ACTION_TIMER_MSEC 10000
#define HELMET_TIMER_MSEC 10000
#define SHOVEL_TIMER_MSEC 20000
#define INIT_INVULNERABILITY_TIMER_MSEC 3000
#define BASE_WALL_BLINK_TIMER_MSEC 500
#define BASE_WALL_FINITE_TIMER_MSEC 4000
#define MV_TIMER_MSEC 50
#define ENEMY_RESPAWN_TIMER_MSEC 3000

#define APPEARANCE_TIME 1000
#define APPEARANCE_DELAY 500

#define TILE_TYPE_SHIFT 4
#define TILE_ORIENTATION_MASK 0b1111
